// File: src/adapters/azure-right.ts

// 5. The Adapters (Logic)

// The Right Enantiomer: Azure Bicep Generator.

import { ChiralSystem } from '../../intent';
import { getRegionalHardwareMap, validateRegionalCapabilities } from '../../translation/hardware-map';

// Azure Bicep configuration options based on community best practices
export interface AzureBicepOptions {
  useAVM?: boolean; // Use Azure Verified Modules
  deploymentMode?: 'incremental' | 'complete' | 'deployment-stacks';
  enableIdempotencyFixes?: boolean; // Handle known Bicep idempotency issues
  enableWhatIf?: boolean; // Enable what-if support
  moduleRegistry?: string; // ACR registry for custom modules
}

// =================================================================
// RIGHT ENANTIOMER (Azure Adapter)
// -----------------------------------------------------------------
// This class acts as a "Printer". It takes the abstract Chiral DNA
// and injects it into a raw Bicep DSL string.
//
// It does NOT validate Bicep syntax (that happens in the build step).
// It ONLY ensures the configuration values are mapped correctly.
// =================================================================

export class AzureBicepAdapter {
  static generate(intent: ChiralSystem, options: AzureBicepOptions = {}): string {
    // Default options based on community best practices
    const opts: AzureBicepOptions = {
      useAVM: options.useAVM ?? true, // Default to AVM for better reliability
      deploymentMode: options.deploymentMode ?? 'incremental',
      enableIdempotencyFixes: options.enableIdempotencyFixes ?? true,
      enableWhatIf: options.enableWhatIf ?? true,
      moduleRegistry: options.moduleRegistry,
      ...options
    };

    // Validate regional capabilities
    const azureRegion = intent.region?.azure || 'eastus';
    const regionalValidation = validateRegionalCapabilities('azure', azureRegion, ['kubernetes', 'postgresql', 'activeDirectory']);

    if (!regionalValidation.valid) {
      throw new Error(`Azure region ${azureRegion} missing required services: ${regionalValidation.missingServices.join(', ')}`);
    }

    // Get region-aware hardware mappings
    const regionalHardware = getRegionalHardwareMap('azure', azureRegion);

    // 1. TRANSLATION (Hardware Mapping)
    // ------------------------------------------------
    // Convert abstract sizes (small/large) into Azure SKUs (Standard_B2s, etc.)
    const dbSku = regionalHardware.db[intent.postgres.size];
    const vmSku = regionalHardware.vm[intent.adfs.size];
    const k8sSku = regionalHardware.k8s[intent.k8s.size];
    
    // Logic: Determine Postgres Tier based on SKU prefix (B=Burstable, D=GeneralPurpose)
    const dbTier = dbSku.startsWith('Standard_B') ? 'Burstable' : 'GeneralPurpose';

    // Logic: Map Windows Version Intent to Azure Image SKU
    const winImageSku = intent.adfs.windowsVersion === '2022' 
      ? '2022-datacenter-azure-edition' 
      : '2019-datacenter';

    // Calculate default subnet CIDR if not provided
    const defaultSubnetCidr = intent.networkCidr.replace(/\/(\d+)$/, (match, mask) => {
      const baseMask = parseInt(mask);
      return `/${baseMask + 8}`; // Add 8 bits for subnet (e.g., /16 -> /24)
    });
    const subnetCidr = intent.network?.subnetCidr || defaultSubnetCidr;

    // Generate Bicep content based on options
    if (opts.useAVM) {
      return this.generateWithAVM(intent, opts, azureRegion, subnetCidr, dbSku, dbTier, vmSku, k8sSku, winImageSku);
    } else {
      return this.generateCustom(intent, opts, azureRegion, subnetCidr, dbSku, dbTier, vmSku, k8sSku, winImageSku);
    }
  }

  private static generateWithAVM(
    intent: ChiralSystem,
    opts: AzureBicepOptions,
    azureRegion: string,
    subnetCidr: string,
    dbSku: string,
    dbTier: string,
    vmSku: string,
    k8sSku: string,
    winImageSku: string
  ): string {
    // Use Azure Verified Modules for production-ready deployments
    return `
@description('Generated by Chiral Engine - DO NOT EDIT MANUALLY')
@description('Deployment mode: ${opts.deploymentMode}')
@description('Using Azure Verified Modules (AVM) for best practices')
param location string = resourceGroup().location

@description('The admin password for both VM and DB (injected at deployment time)')
@secure()
param adminPassword string

@description('Deployment mode configuration')
param deploymentMode string = '${opts.deploymentMode}'

// =================================================================
// 1. NETWORKING (AVM Module)
// =================================================================
module virtualNetwork 'br/public:avm/res/network/virtual-network:0.6.1' = {
  name: 'virtualNetworkDeployment'
  params: {
    name: '${intent.projectName}-vnet'
    addressPrefixes: ['${intent.networkCidr}']
    location: location
    subnets: [
      {
        name: 'default'
        addressPrefix: '${subnetCidr}'
      }
    ]
  }
}

// =================================================================
// 2. KUBERNETES (AKS) - AVM Module with Enhanced Features
// =================================================================
module aks 'br/public:avm/res/container-service/managed-cluster:0.1.0' = {
  name: 'aksDeployment'
  params: {
    name: '${intent.projectName}-aks'
    location: location
    dnsPrefix: '${intent.projectName}-aks'
    kubernetesVersion: '${intent.k8s.version}'
    agentPoolProfiles: [
      {
        name: 'systempool'
        enableAutoScaling: true
        minCount: ${intent.k8s.minNodes}
        maxCount: ${intent.k8s.maxNodes}
        count: ${intent.k8s.minNodes}
        vmSize: '${k8sSku}' // Use the same size as application pool for consistency
        mode: 'System'
        osType: 'Linux'
        orchestratorVersion: '${intent.k8s.version}'
      }
      {
        name: 'applicationpool'
        enableAutoScaling: true
        minCount: ${intent.k8s.minNodes}
        maxCount: ${intent.k8s.maxNodes}
        count: ${intent.k8s.minNodes}
        vmSize: '${k8sSku}'
        mode: 'User'
        osType: 'Linux'
        orchestratorVersion: '${intent.k8s.version}'
      }
    ]
    identity: {
      type: 'SystemAssigned'
    }
    networkProfile: {
      networkPlugin: 'azure'
      networkPolicy: 'azure'
      serviceCidr: '10.0.2.0/24'
      dnsServiceIP: '10.0.2.10'
      dockerBridgeCidr: '172.17.0.1/16'
    }
  }
}

// =================================================================
// 3. DATABASE (PostgreSQL Flexible Server) - AVM Module
// =================================================================
module postgres 'br/public:avm/res/db-for-postgre-sql/flexible-server:0.1.0' = {
  name: 'postgresDeployment'
  params: {
    name: '${intent.projectName}-pg'
    location: location
    skuName: '${dbSku}'
    skuTier: '${dbTier}'
    version: '${intent.postgres.engineVersion}'
    administratorLogin: 'pgadmin'
    administratorLoginPassword: adminPassword
    storageSizeGB: ${intent.postgres.storageGb}
    highAvailabilityMode: '${intent.environment === 'prod' ? 'ZoneRedundant' : 'Disabled'}'
    backupRetentionDays: ${intent.environment === 'prod' ? 30 : 7}
    ${opts.enableIdempotencyFixes ? `
    // Idempotency fixes for known Bicep issues
    createMode: 'Default'
    sourceServerName: ''` : ''}
  }
}

// =================================================================
// 4. ACTIVE DIRECTORY FEDERATION SERVICES (Custom Resources)
// =================================================================

// 4a. Network Interface
resource nic 'Microsoft.Network/networkInterfaces@2023-04-01' = {
  name: '${intent.projectName}-adfs-nic'
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          subnet: {
            id: virtualNetwork.outputs.subnetResourceIds[0]
          }
          privateIPAllocationMethod: 'Dynamic'
        }
      }
    ]
  }
}

// 4b. Virtual Machine
resource adfsVm 'Microsoft.Compute/virtualMachines@2023-03-01' = {
  name: '${intent.projectName}-adfs'
  location: location
  properties: {
    hardwareProfile: {
      vmSize: '${vmSku}' // e.g. Standard_D4s_v3
    }
    osProfile: {
      computerName: 'adfsserver'
      adminUsername: 'localadmin'
      adminPassword: adminPassword
    }
    storageProfile: {
      imageReference: {
        publisher: 'MicrosoftWindowsServer'
        offer: 'WindowsServer'
        sku: '${winImageSku}'
        version: 'latest'
      }
      osDisk: {
        createOption: 'FromImage'
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: nic.id
        }
      ]
    }
  }
}

// 4c. Custom Script Extension (Installs AD FS Role)
resource adfsInstall 'Microsoft.Compute/virtualMachines/extensions@2023-03-01' = {
  parent: adfsVm
  name: 'InstallADFS'
  location: location
  properties: {
    publisher: 'Microsoft.Compute'
    type: 'CustomScriptExtension'
    typeHandlerVersion: '1.10'
    settings: {
      // PowerShell command to install the Windows Feature
      commandToExecute: 'powershell.exe Install-WindowsFeature ADFS-Federation -IncludeManagementTools'
    }
  }
}

// =================================================================
// 5. OUTPUTS
// =================================================================
output vnetId string = virtualNetwork.outputs.resourceId
output aksClusterName string = aks.outputs.name
output postgresEndpoint string = postgres.outputs.fullyQualifiedDomainName
output adfsVmId string = adfsVm.id
output deploymentMode string = deploymentMode
    `.trim();
  }

  private static generateCustom(
    intent: ChiralSystem,
    opts: AzureBicepOptions,
    azureRegion: string,
    subnetCidr: string,
    dbSku: string,
    dbTier: string,
    vmSku: string,
    k8sSku: string,
    winImageSku: string
  ): string {
    // Generate custom Bicep without AVM modules
    return `
@description('Generated by Chiral Engine - DO NOT EDIT MANUALLY')
@description('Deployment mode: ${opts.deploymentMode}')
@description('Using custom Bicep resources')
param location string = resourceGroup().location

@description('The admin password for both VM and DB (injected at deployment time)')
@secure()
param adminPassword string

// =================================================================
// 1. NETWORKING (Custom Resources)
// =================================================================
resource vnet 'Microsoft.Network/virtualNetworks@2023-04-01' = {
  name: '${intent.projectName}-vnet'
  location: location
  properties: {
    addressSpace: {
      addressPrefixes: [
        '${intent.networkCidr}'
      ]
    }
    subnets: [
      {
        name: 'default'
        properties: {
          addressPrefix: '${subnetCidr}'
        }
      }
    ]
  }
}

// =================================================================
// 2. KUBERNETES (AKS) - Custom Resources
// =================================================================
resource aks 'Microsoft.ContainerService/managedClusters@2024-01-01' = {
  name: '${intent.projectName}-aks'
  location: location
  properties: {
    kubernetesVersion: '${intent.k8s.version}'
    dnsPrefix: '${intent.projectName}-aks'
    agentPoolProfiles: [
      {
        name: 'systempool'
        count: ${intent.k8s.minNodes}
        vmSize: '${k8sSku}'
        osType: 'Linux'
        mode: 'System'
        enableAutoScaling: true
        minCount: ${intent.k8s.minNodes}
        maxCount: ${intent.k8s.maxNodes}
      }
      {
        name: 'applicationpool'
        count: ${intent.k8s.minNodes}
        vmSize: '${k8sSku}'
        osType: 'Linux'
        mode: 'User'
        enableAutoScaling: true
        minCount: ${intent.k8s.minNodes}
        maxCount: ${intent.k8s.maxNodes}
      }
    ]
    identity: {
      type: 'SystemAssigned'
    }
    networkProfile: {
      networkPlugin: 'azure'
      networkPolicy: 'azure'
      serviceCidr: '10.0.2.0/24'
      dnsServiceIP: '10.0.2.10'
      dockerBridgeCidr: '172.17.0.1/16'
    }
  }
}

// =================================================================
// 3. DATABASE (PostgreSQL Flexible Server) - Custom Resources
// =================================================================
resource postgres 'Microsoft.DBforPostgreSQL/flexibleServers@2023-06-01-preview' = {
  name: '${intent.projectName}-pg'
  location: location
  properties: {
    version: '${intent.postgres.engineVersion}'
    administratorLogin: 'pgadmin'
    administratorLoginPassword: adminPassword
    storage: {
      storageSizeGB: ${intent.postgres.storageGb}
    }
    sku: {
      name: '${dbSku}'
      tier: '${dbTier}'
    }
    highAvailability: {
      mode: '${intent.environment === 'prod' ? 'ZoneRedundant' : 'Disabled'}'
    }
    backup: {
      backupRetentionDays: ${intent.environment === 'prod' ? 30 : 7}
      geoRedundantBackup: '${intent.environment === 'prod' ? 'Enabled' : 'Disabled'}'
    }
  }
}

// =================================================================
// 4. ACTIVE DIRECTORY FEDERATION SERVICES (Custom Resources)
// =================================================================

// 4a. Network Interface
resource nic 'Microsoft.Network/networkInterfaces@2023-04-01' = {
  name: '${intent.projectName}-adfs-nic'
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          subnet: {
            id: vnet.id
          }
          privateIPAllocationMethod: 'Dynamic'
        }
      }
    ]
  }
}

// 4b. Virtual Machine
resource adfsVm 'Microsoft.Compute/virtualMachines@2023-03-01' = {
  name: '${intent.projectName}-adfs'
  location: location
  properties: {
    hardwareProfile: {
      vmSize: '${vmSku}'
    }
    osProfile: {
      computerName: 'adfsserver'
      adminUsername: 'localadmin'
      adminPassword: adminPassword
    }
    storageProfile: {
      imageReference: {
        publisher: 'MicrosoftWindowsServer'
        offer: 'WindowsServer'
        sku: '${winImageSku}'
        version: 'latest'
      }
      osDisk: {
        createOption: 'FromImage'
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: nic.id
        }
      ]
    }
  }
}

// 4c. Custom Script Extension
resource adfsInstall 'Microsoft.Compute/virtualMachines/extensions@2023-03-01' = {
  parent: adfsVm
  name: 'InstallADFS'
  location: location
  properties: {
    publisher: 'Microsoft.Compute'
    type: 'CustomScriptExtension'
    typeHandlerVersion: '1.10'
    settings: {
      commandToExecute: 'powershell.exe Install-WindowsFeature ADFS-Federation -IncludeManagementTools'
    }
  }
}

// =================================================================
// 5. OUTPUTS
// =================================================================
output vnetId string = vnet.id
output aksClusterName string = aks.name
output postgresEndpoint string = postgres.properties.fullyQualifiedDomainName
output adfsVmId string = adfsVm.id
    `.trim();
  }
}

