// File: src/adapters/declarative/terraform-adapter.ts

// Terraform Adapter for Chiral Infrastructure as Code
// Converts Chiral intent to Terraform HCL configuration

import { ChiralSystem } from '../../intent';
import { getRegionalHardwareMap } from '../../translation/hardware-map';

export interface TerraformConfig {
  provider: 'aws' | 'azure' | 'gcp';
  delegateState?: boolean;
  outputDirectory?: string;
  projectName: string;
  environment: string;
  region?: string;
}

export interface TerraformResource {
  resource: string;
  config: any;
  depends_on?: string[];
}

export class TerraformAdapter {
  static generate(config: ChiralSystem, options: Partial<TerraformConfig> = {}): string {
    const provider = options.provider || 'aws';
    const regionalHardware = getRegionalHardwareMap(provider, config.region?.[provider] || 'us-east-1');
    
    const terraformConfig: TerraformConfig = {
      provider,
      projectName: config.projectName,
      environment: config.environment,
      region: config.region?.[provider] || 'us-east-1',
      delegateState: options.delegateState,
      outputDirectory: options.outputDirectory
    };
    
    return `
# Chiral Infrastructure Configuration
# Generated by Chiral Infrastructure as Code
# Provider: ${provider.toUpperCase()}

terraform {
  required_version = ">= 1.0"
  required_providers {
    ${provider} = {
      source = "hashicorp/${provider}"
      version = "~> 4.0"
    }
  }

# Variables
variable "project_name" {
  description = "Project name"
  type = string
  default = "${terraformConfig.projectName}"
}

variable "environment" {
  description = "Environment"
  type = string
  default = "${terraformConfig.environment}"
}

variable "region" {
  description = "Cloud region"
  type = string
  default = "${terraformConfig.region}"
}

# Provider Configuration
provider "${provider}" {
  region = var.region
  ${options.delegateState ? `
  # State delegation enabled
  # State will be managed by cloud provider
  ` : ''}
}

# Kubernetes Cluster
resource "${provider}_kubernetes_cluster" "main" {
  project_name = var.project_name
  environment = var.environment
  
  k8s = {
    version = "${config.k8s.version}"
    min_nodes = ${config.k8s.minNodes}
    max_nodes = ${config.k8s.maxNodes}
    size = "${config.k8s.size}"
  }
  
  postgres = {
    engine_version = "${config.postgres.engineVersion}"
    size = "${config.postgres.size}"
    storage_gb = ${config.postgres.storageGb}
  }
  
  adfs = {
    size = "${config.adfs.size}"
    windows_version = "${config.adfs.windowsVersion}"
  }
  
  ${options.delegateState ? `
  # State delegation to cloud provider
  lifecycle {
    ignore_changes = all
  }
  ` : ''}
}

# Output
output "cluster_id" {
  description = "Kubernetes cluster ID"
  value = "${provider}_kubernetes_cluster.main.id"
}

output "config" {
  description = "Cluster configuration"
  value = "${provider}_kubernetes_cluster.main.config"
}
    `.trim();
  }

  static generateResources(config: ChiralSystem, options: Partial<TerraformConfig> = {}): TerraformResource[] {
    const provider = options.provider || 'aws';
    const resources: TerraformResource[] = [];
    
    // Kubernetes cluster resource
    resources.push({
      resource: `${provider}_kubernetes_cluster`,
      config: {
        project_name: config.projectName,
        environment: config.environment,
        k8s: config.k8s,
        postgres: config.postgres,
        adfs: config.adfs,
        output_directory: options.outputDirectory
      }
    });
    
    return resources;
  }
}
