import { AzureBicepAdapter } from '../adapters/declarative/azure-bicep';
import { ChiralSystem } from '../intent';

describe('AzureBicepAdapter', () => {
  const testIntent: ChiralSystem = {
    projectName: 'test-project',
    environment: 'prod',
    networkCidr: '10.0.0.0/16',
    k8s: {
      version: '1.29',
      minNodes: 2,
      maxNodes: 5,
      size: 'large'
    },
    postgres: {
      engineVersion: '15',
      size: 'large',
      storageGb: 100
    },
    adfs: {
      size: 'large',
      windowsVersion: '2022'
    }
  };

  describe('synthesize method', () => {
    it('should generate valid Bicep template', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('@description(\'Generated by Chiral Engine - DO NOT EDIT MANUALLY\')');
      expect(result).toContain('param location string = resourceGroup().location');
      expect(result).toContain('param adminPassword string');
      expect(result).toContain('resource vnet \'Microsoft.Network/virtualNetworks@2023-04-01\'');
      expect(result).toContain('resource aks \'Microsoft.ContainerService/managedClusters@2024-01-01\'');
      expect(result).toContain('resource postgres \'Microsoft.DBforPostgreSQL/flexibleServers@2023-06-01-preview\'');
      expect(result).toContain('resource adfsVm \'Microsoft.Compute/virtualMachines@2023-03-01\'');
    });

    it('should include project name in resource names', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('test-project-vnet');
      expect(result).toContain('test-project-aks');
      expect(result).toContain('test-project-pg');
      expect(result).toContain('test-project-adfs');
    });

    it('should use correct Kubernetes version', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('kubernetesVersion: \'1.29\'');
    });

    it('should use correct PostgreSQL version', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('version: \'15\'');
    });

    it('should use correct Windows version for AD FS', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('2022-datacenter-azure-edition');
    });

    it('should use HardwareMap values for sizing', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      // Should use large sizes from HardwareMap
      expect(result).toContain('Standard_D4s_v3'); // Large VM/DB size
    });

    it('should configure production settings correctly', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toContain('ZoneRedundant'); // High availability for prod
      expect(result).toContain('backupRetentionDays: 30'); // Prod backup retention
    });

    it('should return a string', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(typeof result).toBe('string');
      expect(result.length).toBeGreaterThan(0);
    });

    it('should trim whitespace', () => {
      const result = AzureBicepAdapter.synthesize(testIntent);

      expect(result).toBe(result.trim());
    });
  });

  describe('environment-specific behavior', () => {
    it('should configure prod environment correctly', () => {
      const prodIntent = { ...testIntent, environment: 'prod' as const };
      const result = AzureBicepAdapter.synthesize(prodIntent);

      expect(result).toContain('count: 2'); // Prod min nodes
      expect(result).toContain('ZoneRedundant');
      expect(result).toContain('backupRetentionDays: 30');
    });

    it('should configure dev environment correctly', () => {
      const devIntent = { ...testIntent, environment: 'dev' as const };
      const result = AzureBicepAdapter.synthesize(devIntent);

      expect(result).toContain('count: 1'); // Dev min nodes
      expect(result).toContain('Disabled'); // No HA for dev
      expect(result).toContain('backupRetentionDays: 7');
    });
  });
});
