// File: src/adapters/azure-right.ts

// 5. The Adapters (Logic)

// The Right Enantiomer: Azure Bicep Generator.

import { ChiralSystem } from '../intent';
import { HardwareMap } from '../rosetta/hardware-map';

// =================================================================
// RIGHT ENANTIOMER (Azure Adapter)
// -----------------------------------------------------------------
// This class acts as a "Printer". It takes the abstract Chiral DNA
// and injects it into a raw Bicep DSL string.
//
// It does NOT validate Bicep syntax (that happens in the build step).
// It ONLY ensures the configuration values are mapped correctly.
// =================================================================

export class AzureRightHandAdapter {
  static synthesize(intent: ChiralSystem): string {
    // 1. ROSETTA TRANSLATION (Hardware Mapping)
    // ------------------------------------------------
    // Convert abstract sizes (small/large) into Azure SKUs (Standard_B2s, etc.)
    const dbSku = HardwareMap.azure.db[intent.postgres.size];
    const vmSku = HardwareMap.azure.vm[intent.adfs.size];
    const k8sSku = HardwareMap.azure.k8s[intent.k8s.size];
    
    // Logic: Determine Postgres Tier based on SKU prefix (B=Burstable, D=GeneralPurpose)
    const dbTier = dbSku.startsWith('Standard_B') ? 'Burstable' : 'GeneralPurpose';

    // Logic: Map Windows Version Intent to Azure Image SKU
    const winImageSku = intent.adfs.windowsVersion === '2022' 
      ? '2022-datacenter-azure-edition' 
      : '2019-datacenter';

    // 2. BICEP TEMPLATE GENERATION ("Mad Libs")
    // ------------------------------------------------
    // The content inside the backticks (`) IS the Bicep DSL.
    // We use ${variable} to inject the strict configuration.
    
    return `
@description('Generated by Chiral Engine - DO NOT EDIT MANUALLY')
param location string = resourceGroup().location

@description('The admin password for both VM and DB (injected at deployment time)')
@secure()
param adminPassword string

// =================================================================
// 1. NETWORKING
// =================================================================
resource vnet 'Microsoft.Network/virtualNetworks@2023-04-01' = {
  name: '${intent.projectName}-vnet'
  location: location
  properties: {
    addressSpace: {
      addressPrefixes: ['${intent.networkCidr}'] 
    }
    subnets: [
      {
        name: 'default'
        properties: {
          addressPrefix: '10.0.1.0/24'
        }
      }
    ]
  }
}

// =================================================================
// 2. KUBERNETES (AKS)
// =================================================================
resource aks 'Microsoft.ContainerService/managedClusters@2024-01-01' = {
  name: '${intent.projectName}-aks'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    dnsPrefix: '${intent.projectName}-aks'
    kubernetesVersion: '${intent.k8s.version}'
    agentPoolProfiles: [
      {
        name: 'systempool'
        count: ${intent.environment === 'prod' ? 2 : 1}
        vmSize: 'Standard_D2s_v3' // System nodes usually fixed size
        mode: 'System'
        osType: 'Linux'
        orchestratorVersion: '${intent.k8s.version}'
      }
      {
        name: 'applicationpool'
        count: 2
        vmSize: '${k8sSku}'
        mode: 'User'
        osType: 'Linux'
        orchestratorVersion: '${intent.k8s.version}'
      }
    ]
    networkProfile: {
      networkPlugin: 'azure'
      networkPolicy: 'azure'
      serviceCidr: '10.0.2.0/24'
      dnsServiceIP: '10.0.2.10'
      dockerBridgeCidr: '172.17.0.1/16'
    }
  }
}

// =================================================================
// 3. DATABASE (PostgreSQL Flexible Server)
// =================================================================
resource postgres 'Microsoft.DBforPostgreSQL/flexibleServers@2023-06-01-preview' = {
  name: '${intent.projectName}-pg'
  location: location
  sku: {
    name: '${dbSku}'      // e.g. Standard_D4s_v3
    tier: '${dbTier}'     // e.g. GeneralPurpose
  }
  properties: {
    version: '${intent.postgres.engineVersion}'
    administratorLogin: 'pgadmin'
    administratorLoginPassword: adminPassword
    storage: {
      storageSizeGB: ${intent.postgres.storageGb}
    }
    highAvailability: {
      mode: '${intent.environment === 'prod' ? 'ZoneRedundant' : 'Disabled'}'
    }
    backup: {
      backupRetentionDays: ${intent.environment === 'prod' ? 30 : 7}
    }
  }
}

// =================================================================
// 4. ACTIVE DIRECTORY FEDERATION SERVICES (Windows VM)
// =================================================================

// 4a. Network Interface
resource nic 'Microsoft.Network/networkInterfaces@2023-04-01' = {
  name: '${intent.projectName}-adfs-nic'
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          subnet: {
            id: vnet.properties.subnets[0].id
          }
          privateIPAllocationMethod: 'Dynamic'
        }
      }
    ]
  }
}

// 4b. Virtual Machine
resource adfsVm 'Microsoft.Compute/virtualMachines@2023-03-01' = {
  name: '${intent.projectName}-adfs'
  location: location
  properties: {
    hardwareProfile: {
      vmSize: '${vmSku}' // e.g. Standard_D4s_v3
    }
    osProfile: {
      computerName: 'adfsserver'
      adminUsername: 'localadmin'
      adminPassword: adminPassword
    }
    storageProfile: {
      imageReference: {
        publisher: 'MicrosoftWindowsServer'
        offer: 'WindowsServer'
        sku: '${winImageSku}'
        version: 'latest'
      }
      osDisk: {
        createOption: 'FromImage'
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: nic.id
        }
      ]
    }
  }
}

// 4c. Custom Script Extension (Installs AD FS Role)
resource adfsInstall 'Microsoft.Compute/virtualMachines/extensions@2023-03-01' = {
  parent: adfsVm
  name: 'InstallADFS'
  location: location
  properties: {
    publisher: 'Microsoft.Compute'
    type: 'CustomScriptExtension'
    typeHandlerVersion: '1.10'
    settings: {
      // PowerShell command to install the Windows Feature
      commandToExecute: 'powershell.exe Install-WindowsFeature ADFS-Federation -IncludeManagementTools'
    }
  }
}

// =================================================================
// 5. OUTPUTS
// =================================================================
output vnetId string = vnet.id
output aksClusterName string = aks.name
output postgresEndpoint string = postgres.properties.fullyQualifiedDomainName
output adfsVmId string = adfsVm.id
    `.trim();
  }
}

