# Example Terraform Bridge Configuration
# Generated by Chiral for gradual migration from Terraform to native cloud state

terraform {
  required_version = ">= 1.0"
  
  # Cloud provider configuration
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
  
  # Delegate state management to CloudFormation (eliminates Terraform state issues)
  backend "aws" {
    alias = "aws"
    region = var.aws_region
  }
  
  # Variables
  variable "aws_region" {
    description = "AWS region for deployment"
    type        = string
    default     = "us-east-1"
  }
  
  variable "project_name" {
    description = "Project name for resource naming"
    type        = string
  }
  
  # EKS cluster managed by CloudFormation (no Terraform state)
  resource "aws_cloudformation_stack" "eks_cluster" {
    name = "${var.project_name}-eks"
    template = file("terraform-templates/eks-template.json")
    
    # CloudFormation handles state internally
    # No more Terraform state corruption, lock contention, or backend management
  }
  
  # RDS database managed by CloudFormation (no Terraform state)
  resource "aws_cloudformation_stack" "rds_database" {
    name = "${var.project_name}-database"
    template = file("terraform-templates/rds-template.json")
    
    # CloudFormation handles state internally
    # No more Terraform state corruption, lock contention, or backend management
  }
  
  # Traditional VPC (kept for comparison during migration)
  resource "aws_vpc" "legacy_vpc" {
    cidr_block = "10.0.0.0/16"
    
    tags = {
      Name        = "${var.project_name}-legacy"
      Migration = "true"
    }
  }
}

# Output
output "terraform_bridge_note" {
  description = "Terraform Bridge: State delegated to CloudFormation"
  value       = "Traditional Terraform state issues eliminated by using CloudFormation-managed resources"
}
