// File: src/utils/terraform-hcl.ts

// HCL generation utilities for Terraform provider

import { TerraformConfig } from '../adapters/declarative/terraform-adapter';

export function generateTerraformHcl(config: TerraformConfig): string {
  return `
# Chiral Infrastructure Configuration
# Generated by Chiral Infrastructure as Code
# Provider: ${config.provider.toUpperCase()}

terraform {
  required_version = ">= 1.0"
  required_providers {
    ${config.provider} = {
      source = "hashicorp/${config.provider}"
      version = "~> 4.0"
    }
  }
}

# Variables
variable "project_name" {
  description = "Project name"
  type = string
  default = "${config.projectName}"
}

variable "environment" {
  description = "Environment"
  type = string
  default = "${config.environment}"
}

variable "region" {
  description = "Cloud region"
  type = string
  default = "${config.region || 'us-east-1'}"
}

# Provider Configuration
provider "${config.provider}" {
  region = var.region
  ${config.delegateState ? `
  # State delegation enabled
  # State will be managed by cloud provider
  ` : ''}
}

# Kubernetes Cluster
resource "${config.provider}_kubernetes_cluster" "main" {
  project_name = var.project_name
  environment = var.environment
  
  k8s = {
    version = "1.35"
    min_nodes = 1
    max_nodes = 3
    size = "small"
  }
  
  postgres = {
    engine_version = "18.3"
    size = "small"
    storage_gb = 20
  }
  
  adfs = {
    size = "small"
    windows_version = "11 26H2 Build 26300.7877"
  }
  
  ${config.delegateState ? `
  # State delegation to cloud provider
  lifecycle {
    ignore_changes = all
  }
  ` : ''}
}

# Output
output "cluster_id" {
  description = "Kubernetes cluster ID"
  value = "${config.provider}_kubernetes_cluster.main.id"
}

output "config" {
  description = "Cluster configuration"
  value = "${config.provider}_kubernetes_cluster.main.config"
}
  `.trim();
}
