// File: src/cost-analysis.ts

// Cost analysis and estimation capabilities for Chiral Infrastructure as Code
// Integrates with azure-cost-cli for Azure, Infracost for AWS/GCP pricing data

import { ChiralSystem } from './intent';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

export interface CostEstimate {
  provider: 'aws' | 'azure' | 'gcp';
  totalMonthlyCost: number;
  currency: string;
  breakdown: CostBreakdown;
  recommendations: string[];
  warnings: string[];
}

export interface CostBreakdown {
  compute: {
    kubernetes: number;
    vm: number;
    total: number;
  };
  storage: {
    database: number;
    vmDisk: number;
    total: number;
  };
  network: {
    dataTransfer: number;
    loadBalancer: number;
    total: number;
  };
  other: {
    management: number;
    monitoring: number;
    total: number;
  };
}

export interface CostComparison {
  cheapest: {
    provider: 'aws' | 'azure' | 'gcp';
    cost: number;
    savings: number; // percentage savings vs most expensive
  };
  mostExpensive: {
    provider: 'aws' | 'azure' | 'gcp';
    cost: number;
  };
  estimates: {
    aws: CostEstimate;
    azure: CostEstimate;
    gcp: CostEstimate;
  };
}

export interface CostAnalysisOptions {
  region?: string;
  currency?: string;
  includeRecommendations?: boolean;
  detailed?: boolean;
  timeframe?: 'hourly' | 'daily' | 'monthly' | 'yearly';
}

// =================================================================
// MULTI-CLOUD COST ANALYSIS TOOLS
// =================================================================

export class InfracostAnalyzer {
  private static readonly INFRACOST_CLI = 'infracost';

  static isAvailable(): boolean {
    try {
      execSync(`${this.INFRACOST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  static async getAWSPricing(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || config.region?.aws || 'us-east-1';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      console.warn('Infracost not found, using fallback AWS pricing estimation');
      return this.getFallbackAWSPricing(config, region, currency);
    }

    try {
      // Generate temporary CloudFormation template for Infracost analysis
      const tempTemplate = await this.generateAWSTemplate(config, region);
      const pricingData = await this.fetchInfracostPricing(tempTemplate, 'aws', region);
      
      // Clean up temporary file
      if (fs.existsSync(tempTemplate)) fs.unlinkSync(tempTemplate);
      
      return this.calculateAWSCosts(config, pricingData, region, currency);
    } catch (error) {
      console.warn('Failed to fetch AWS pricing data, using fallback:', error);
      return this.getFallbackAWSPricing(config, region, currency);
    }
  }

  static async getGCPPricing(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || config.region?.gcp || 'us-central1';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      console.warn('Infracost not found, using fallback GCP pricing estimation');
      return this.getFallbackGCPPricing(config, region, currency);
    }

    try {
      // Generate temporary Terraform template for Infracost analysis
      const tempTemplate = await this.generateGCPTemplate(config, region);
      const pricingData = await this.fetchInfracostPricing(tempTemplate, 'gcp', region);
      
      // Clean up temporary file
      if (fs.existsSync(tempTemplate)) fs.unlinkSync(tempTemplate);
      
      return this.calculateGCPCosts(config, pricingData, region, currency);
    } catch (error) {
      console.warn('Failed to fetch GCP pricing data, using fallback:', error);
      return this.getFallbackGCPPricing(config, region, currency);
    }
  }

  private static async generateAWSTemplate(config: ChiralSystem, region: string): Promise<string> {
    // Generate CloudFormation template matching AWS CDK output
    const template = {
      AWSTemplateFormatVersion: '2010-09-09',
      Description: `Generated by Chiral Engine - ${config.projectName}`,
      Parameters: {
        Environment: { Type: 'String', Default: config.environment },
        ProjectName: { Type: 'String', Default: config.projectName }
      },
      Resources: {
        // EKS Cluster
        EKSCluster: {
          Type: 'AWS::EKS::Cluster',
          Properties: {
            Name: `${config.projectName}-eks`,
            Version: config.k8s.version,
            ResourcesVpcConfig: {
              EndpointPublicAccess: true
            }
          }
        },
        // EKS Node Group
        EKSNodeGroup: {
          Type: 'AWS::EKS::Nodegroup',
          Properties: {
            ClusterName: { Ref: 'EKSCluster' },
            NodegroupName: `${config.projectName}-nodes`,
            ScalingConfig: {
              MinSize: config.k8s.minNodes,
              MaxSize: config.k8s.maxNodes,
              DesiredSize: config.k8s.minNodes
            },
            InstanceTypes: [this.getAWSInstanceType(config.k8s.size)]
          }
        },
        // RDS PostgreSQL
        RDSInstance: {
          Type: 'AWS::RDS::DBInstance',
          Properties: {
            DBInstanceIdentifier: `${config.projectName}-postgres`,
            DBInstanceClass: this.getRDSInstanceClass(config.postgres.size),
            Engine: 'postgres',
            EngineVersion: config.postgres.engineVersion,
            AllocatedStorage: config.postgres.storageGb,
            StorageType: 'gp2'
          }
        },
        // EC2 Instance for AD FS
        ADFSInstance: {
          Type: 'AWS::EC2::Instance',
          Properties: {
            InstanceType: this.getAWSInstanceType(config.adfs.size),
            ImageId: this.getWindowsAMI(config.adfs.windowsVersion)
          }
        }
      }
    };

    const tempPath = path.join(require('os').tmpdir(), `chiral-aws-${Date.now()}.yaml`);
    const yaml = require('js-yaml');
    fs.writeFileSync(tempPath, yaml.dump(template));
    return tempPath;
  }

  private static async generateGCPTemplate(config: ChiralSystem, region: string): Promise<string> {
    // Generate Terraform template matching GCP adapter output
    const template = `
# Generated by Chiral Engine - ${config.projectName}
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "~> 4.0"
    }
  }
}

provider "google" {
  region = "${region}"
}

# GKE Cluster
resource "google_container_cluster" "primary" {
  name     = "${config.projectName}-gke"
  location = "${region}"
  
  min_master_version = "${config.k8s.version}"
  
  node_pool {
    name       = "default-pool"
    node_count = ${config.k8s.minNodes}
    
    node_config {
      machine_type = "${this.getGCPMachineType(config.k8s.size)}"
    }
    
    autoscaling {
      min_node_count = ${config.k8s.minNodes}
      max_node_count = ${config.k8s.maxNodes}
    }
  }
}

# Cloud SQL PostgreSQL
resource "google_sql_database_instance" "postgres" {
  name             = "${config.projectName}-postgres"
  database_version = "POSTGRES_${config.postgres.engineVersion}"
  region           = "${region}"
  
  settings {
    tier = "${this.getCloudSQLTier(config.postgres.size)}"
    disk_size = ${config.postgres.storageGb}
  }
}

# Compute Engine Instance for AD FS
resource "google_compute_instance" "adfs" {
  name         = "${config.projectName}-adfs"
  machine_type = "${this.getGCPMachineType(config.adfs.size)}"
  zone         = "${region}-a"
  
  boot_disk {
    initialize_params {
      image = "windows-cloud/windows-${config.adfs.windowsVersion}"
    }
  }
}
`;

    const tempPath = path.join(require('os').tmpdir(), `chiral-gcp-${Date.now()}.tf`);
    fs.writeFileSync(tempPath, template);
    return tempPath;
  }

  private static async fetchInfracostPricing(templatePath: string, provider: string, region: string): Promise<any> {
    // Use Infracost to get real pricing data
    const cmd = `${this.INFRACOST_CLI} breakdown --path ${templatePath} --format json --usage-file /dev/null`;
    
    try {
      const result = execSync(cmd, { encoding: 'utf8', stdio: 'pipe' });
      const data = JSON.parse(result);
      
      return {
        totalMonthlyCost: data.summary.totalMonthlyCost || 0,
        breakdown: this.parseInfracostBreakdown(data.projects?.[0]?.breakdown || []),
        resources: data.projects?.[0]?.resources || []
      };
    } catch (error) {
      console.warn(`Infracost command failed: ${cmd}`);
      throw error;
    }
  }

  private static parseInfracostBreakdown(breakdown: any[]): any {
    const parsed: any = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    breakdown.forEach(item => {
      const cost = item.cost || 0;
      const name = item.name?.toLowerCase() || '';
      
      if (name.includes('eks') || name.includes('gke') || name.includes('kubernetes')) {
        parsed.compute.kubernetes += cost;
      } else if (name.includes('ec2') || name.includes('compute')) {
        parsed.compute.vm += cost;
      } else if (name.includes('rds') || name.includes('sql') || name.includes('database')) {
        parsed.storage.database += cost;
      } else if (name.includes('ebs') || name.includes('disk') || name.includes('storage')) {
        parsed.storage.vmDisk += cost;
      } else if (name.includes('load') || name.includes('network')) {
        parsed.network.loadBalancer += cost;
      } else {
        parsed.other.management += cost;
      }
    });

    // Calculate totals
    parsed.compute.total = parsed.compute.kubernetes + parsed.compute.vm;
    parsed.storage.total = parsed.storage.database + parsed.storage.vmDisk;
    parsed.network.total = parsed.network.dataTransfer + parsed.network.loadBalancer;
    parsed.other.total = parsed.other.management + parsed.other.monitoring;

    return parsed;
  }

  private static calculateAWSCosts(config: ChiralSystem, pricingData: any, region: string, currency: string): CostEstimate {
    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Use Infracost data or fallback
    const breakdown = pricingData.breakdown || this.getFallbackAWSBreakdown(config);
    const totalMonthlyCost = pricingData.totalMonthlyCost || Object.values(breakdown).reduce((sum: number, cat: any) => sum + cat.total, 0);

    // Generate recommendations
    if (config.environment === 'prod') {
      recommendations.push('Consider Reserved Instances for production workloads to save up to 40%');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High estimated monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  private static calculateGCPCosts(config: ChiralSystem, pricingData: any, region: string, currency: string): CostEstimate {
    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Use Infracost data or fallback
    const breakdown = pricingData.breakdown || this.getFallbackGCPBreakdown(config);
    const totalMonthlyCost = pricingData.totalMonthlyCost || Object.values(breakdown).reduce((sum: number, cat: any) => sum + cat.total, 0);

    // Generate recommendations
    if (config.environment === 'prod') {
      recommendations.push('Use Committed Use Discounts for predictable workloads to save up to 30%');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High estimated monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  private static getFallbackAWSPricing(config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown = this.getFallbackAWSBreakdown(config);
    const totalMonthlyCost = Object.values(breakdown).reduce((sum, cat) => sum + cat.total, 0);

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Install Infracost for more accurate AWS pricing'],
      warnings: ['Using fallback pricing - install Infracost for accurate costs']
    };
  }

  private static getFallbackGCPPricing(config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown = this.getFallbackGCPBreakdown(config);
    const totalMonthlyCost = Object.values(breakdown).reduce((sum, cat) => sum + cat.total, 0);

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Install Infracost for more accurate GCP pricing'],
      warnings: ['Using fallback pricing - install Infracost for accurate costs']
    };
  }

  private static getFallbackAWSBreakdown(config: ChiralSystem): CostBreakdown {
    return {
      compute: { kubernetes: config.k8s.maxNodes * 145, vm: 95, total: 0 },
      storage: { database: config.postgres.storageGb * 0.23 + 55, vmDisk: 18, total: 0 },
      network: { dataTransfer: 25, loadBalancer: 25, total: 0 },
      other: { management: 35, monitoring: 18, total: 0 }
    };
  }

  private static getFallbackGCPBreakdown(config: ChiralSystem): CostBreakdown {
    return {
      compute: { kubernetes: config.k8s.maxNodes * 140, vm: 90, total: 0 },
      storage: { database: config.postgres.storageGb * 0.25 + 50, vmDisk: 17, total: 0 },
      network: { dataTransfer: 22, loadBalancer: 20, total: 0 },
      other: { management: 32, monitoring: 16, total: 0 }
    };
  }

  // Helper methods for resource type mapping
  private static getAWSInstanceType(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 't3.small',
      'large': 't3.xlarge'
    };
    return sizeMap[size] || 't3.small';
  }

  private static getRDSInstanceClass(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'db.t3.small',
      'large': 'db.m5.large'
    };
    return sizeMap[size] || 'db.t3.small';
  }

  private static getWindowsAMI(version: string): string {
    const amiMap: { [key: string]: string } = {
      '2019': 'ami-0b0a80e1a8ac3e362',
      '2022': 'ami-0d3513f1e7c5a0e7c'
    };
    return amiMap[version] || amiMap['2022'];
  }

  private static getGCPMachineType(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'e2-micro',
      'large': 'n1-standard-2'
    };
    return sizeMap[size] || 'e2-micro';
  }

  private static getCloudSQLTier(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'db-f1-micro',
      'large': 'db-n1-standard-2'
    };
    return sizeMap[size] || 'db-n1-standard-2';
  }
}

// =================================================================
// AWS COST ANALYSIS EQUIVALENTS
// =================================================================

export class AWSCostAnalyzer {
  private static readonly INFRACOST_CLI = 'infracost';
  private static readonly AWS_CLI = 'aws';
  private static readonly AWS_COST_CLI = 'aws-cost-cli';

  static isAvailable(): boolean {
    try {
      execSync(`${this.INFRACOST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      try {
        execSync(`${this.AWS_CLI} --version`, { stdio: 'ignore' });
        return true;
      } catch {
        try {
          execSync(`${this.AWS_COST_CLI} --version`, { stdio: 'ignore' });
          return true;
        } catch {
          return false;
        }
      }
    }
  }

  static isAWSCostCliAvailable(): boolean {
    try {
      execSync(`${this.AWS_COST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  static async getAWSPricing(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || config.region?.aws || 'us-east-1';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      console.warn('AWS CLI or infracost not found, using fallback pricing estimation');
      return this.getFallbackAWSPricing(config, region, currency);
    }

    try {
      // Try to use infracost first (more comprehensive)
      if (this.isInfracostAvailable()) {
        return this.getInfracostPricing(config, region, currency);
      }
      // Fallback to AWS Pricing API
      else {
        return this.getAWSPricingData(config, region, currency);
      }
    } catch (error) {
      console.warn('Failed to fetch AWS pricing data, using fallback:', error);
      return this.getFallbackAWSPricing(config, region, currency);
    }
  }

  private static isInfracostAvailable(): boolean {
    try {
      execSync(`${this.INFRACOST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  private static async getInfracostPricing(config: ChiralSystem, region: string, currency: string): Promise<CostEstimate> {
    // Generate temporary Terraform for infracost analysis
    const tempTfPath = await this.generateTempTerraform(config, region);
    
    try {
      // Run infracost breakdown
      const result = execSync(`${this.INFRACOST_CLI} breakdown --path ${tempTfPath} --format json`, { encoding: 'utf8' });
      const infracostData = JSON.parse(result);
      
      return this.parseInfracostData(infracostData, config, region, currency);
    } finally {
      // Clean up temp files
      try {
        fs.rmSync(tempTfPath, { recursive: true, force: true });
      } catch {
        // Ignore cleanup errors
      }
    }
  }

  private static async generateTempTerraform(config: ChiralSystem, region: string): Promise<string> {
    const tempDir = fs.mkdtempSync('chiral-aws-cost-');
    const tfPath = path.join(tempDir, 'main.tf');
    
    // Generate minimal Terraform for cost estimation
    const tfContent = `
provider "aws" {
  region = "${region}"
}

resource "aws_eks_cluster" "main" {
  name     = "${config.projectName}-eks"
  role_arn  = "arn:aws:iam::123456789012:role/eks-service-role"
  version  = "${config.k8s.version}"

  vpc_config {
    subnet_ids = ["subnet-12345", "subnet-67890"]
  }
}

resource "aws_eks_node_group" "main" {
  cluster_name    = aws_eks_cluster.main.name
  node_group_name = "${config.projectName}-nodes"
  node_role_arn   = "arn:aws:iam::123456789012:role/eks-node-role"
  subnet_ids      = ["subnet-12345", "subnet-67890"]
  
  scaling_config {
    desired_size = ${config.k8s.maxNodes}
    min_size     = ${config.k8s.minNodes}
    max_size     = ${config.k8s.maxNodes}
  }

  instance_types = ["${this.getAWSInstanceType(config.k8s.size)}"]
}

resource "aws_db_instance" "main" {
  identifier     = "${config.projectName}-db"
  engine         = "postgres"
  engine_version = "${config.postgres.engineVersion}"
  instance_class = "${this.getAWSDBInstanceClass(config.postgres.size)}"
  allocated_storage = ${config.postgres.storageGb}
  
  username = "postgres"
  password = "password123"
}

resource "aws_instance" "adfs" {
  ami           = "ami-0c02fb55956c7d316" // Windows Server
  instance_type = "${this.getAWSInstanceType(config.adfs.size)}"
}
`;
    
    fs.writeFileSync(tfPath, tfContent);
    return tempDir;
  }

  private static parseInfracostData(data: any, config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Parse infracost data
    let totalMonthlyCost = 0;
    if (data.projects && data.projects[0] && data.projects[0].breakdown) {
      const breakdownData = data.projects[0].breakdown;
      
      breakdownData.resources?.forEach((resource: any) => {
        const cost = resource.monthlyCost || 0;
        totalMonthlyCost += cost;
        
        // Categorize costs
        if (resource.name.includes('eks') || resource.name.includes('node')) {
          breakdown.compute.kubernetes += cost;
        } else if (resource.name.includes('instance')) {
          breakdown.compute.vm += cost;
        } else if (resource.name.includes('db') || resource.name.includes('rds')) {
          breakdown.storage.database += cost;
        } else if (resource.name.includes('ebs') || resource.name.includes('storage')) {
          breakdown.storage.vmDisk += cost;
        } else if (resource.name.includes('network') || resource.name.includes('vpc')) {
          breakdown.network.dataTransfer += cost;
        } else if (resource.name.includes('lb') || resource.name.includes('load')) {
          breakdown.network.loadBalancer += cost;
        } else {
          breakdown.other.management += cost;
        }
      });
    }

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    // Generate recommendations
    if (config.environment === 'dev' && config.k8s.maxNodes > 3) {
      recommendations.push('Consider using smaller instances for development environment');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High estimated monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  private static async getAWSPricingData(config: ChiralSystem, region: string, currency: string): Promise<CostEstimate> {
    // Use AWS Pricing API
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    try {
      // Get EKS pricing
      const eksPricing = await this.getEKSPricing(region);
      breakdown.compute.kubernetes = eksPricing.managementFee + (eksPricing.nodeCost * config.k8s.maxNodes);

      // Get EC2 pricing
      const ec2Pricing = await this.getEC2Pricing(this.getAWSInstanceType(config.k8s.size), region);
      breakdown.compute.vm = ec2Pricing.hourly * 730; // Monthly approximation

      // Get RDS pricing
      const rdsPricing = await this.getRDSPricing(this.getAWSDBInstanceClass(config.postgres.size), region);
      breakdown.storage.database = rdsPricing.compute + (config.postgres.storageGb * rdsPricing.storagePerGb);

      // Get networking costs
      breakdown.network.dataTransfer = 50 * 0.09; // 50GB data transfer
      breakdown.network.loadBalancer = 25; // ALB monthly cost

      // Management and monitoring
      breakdown.other.management = 30;
      breakdown.other.monitoring = 15;

    } catch (error) {
      console.warn('AWS Pricing API call failed, using estimates:', error);
      return this.getFallbackAWSPricing(config, region, currency);
    }

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Consider Reserved Instances for production workloads'],
      warnings: []
    };
  }

  private static getFallbackAWSPricing(config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    // Simplified fallback pricing
    breakdown.compute.kubernetes = config.k8s.maxNodes * 145; // EKS pricing
    breakdown.compute.vm = 95; // EC2 instance
    breakdown.storage.database = config.postgres.storageGb * 0.23 + 55; // RDS
    breakdown.storage.vmDisk = 18; // EBS volume
    breakdown.network.dataTransfer = 25; // Data transfer
    breakdown.network.loadBalancer = 25; // ELB
    breakdown.other.management = 35;
    breakdown.other.monitoring = 18;

    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Install infracost or AWS CLI for more accurate pricing'],
      warnings: ['Using fallback pricing - install infracost for accurate costs']
    };
  }

  private static async getEKSPricing(region: string): Promise<{ managementFee: number; nodeCost: number }> {
    return { managementFee: 73, nodeCost: 72 }; // Simplified EKS pricing
  }

  private static async getEC2Pricing(instanceType: string, region: string): Promise<{ hourly: number }> {
    const pricingMap: { [key: string]: number } = {
      't3.medium': 0.0416,
      't3.large': 0.0832,
      't3.xlarge': 0.1664
    };
    return { hourly: pricingMap[instanceType] || 0.0832 };
  }

  private static async getRDSPricing(instanceClass: string, region: string): Promise<{ compute: number; storagePerGb: number }> {
    const pricingMap: { [key: string]: { compute: number; storagePerGb: number } } = {
      'db.t3.medium': { compute: 55, storagePerGb: 0.23 },
      'db.t3.large': { compute: 110, storagePerGb: 0.23 },
      'db.t3.xlarge': { compute: 220, storagePerGb: 0.23 }
    };
    return pricingMap[instanceClass] || { compute: 110, storagePerGb: 0.23 };
  }

  private static getAWSInstanceType(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 't3.small',
      'large': 'm5.xlarge'
    };
    return sizeMap[size] || 't3.small';
  }

  private static getAWSDBInstanceClass(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'db.t3.small',
      'large': 'db.m5.large'
    };
    return sizeMap[size] || 'db.t3.small';
  }

  static async analyzeAWSCosts(accountId: string, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || 'us-east-1';
    const currency = options.currency || 'USD';

    if (!this.isAWSCostCliAvailable()) {
      throw new Error('aws-cost-cli not available. Install with: npm install -g aws-cost-cli');
    }

    try {
      // Use aws-cost-cli to analyze actual costs
      const costData = await this.fetchAWSCostData(accountId, region);
      return this.calculateAWSAnalysisCosts(costData, region, currency);
    } catch (error) {
      console.warn('Failed to analyze AWS costs:', error);
      throw error;
    }
  }

  private static async fetchAWSCostData(accountId: string, region: string): Promise<any> {
    // Use aws-cost-cli to get actual billing data
    // This is a placeholder for actual aws-cost-cli integration
    // Example: execSync(`aws-cost-cli analyze --account ${accountId} --region ${region} --format json`);
    
    // For now, return mock data structure that aws-cost-cli would provide
    return {
      accountId,
      region,
      services: {
        'Amazon Elastic Compute Cloud - Compute': {
          totalCost: 250.50,
          resources: [
            { name: 'i-1234567890abcdef0', cost: 95.20, type: 'EC2 Instance' },
            { name: 'eks-cluster-nodes', cost: 155.30, type: 'EKS Nodes' }
          ]
        },
        'Amazon Relational Database Service': {
          totalCost: 180.75,
          resources: [
            { name: 'postgres-db', cost: 180.75, type: 'RDS Instance' }
          ]
        },
        'Amazon Simple Storage Service': {
          totalCost: 45.30,
          resources: [
            { name: 's3-bucket-1', cost: 45.30, type: 'S3 Storage' }
          ]
        }
      },
      totalMonthlyCost: 476.55
    };
  }

  private static calculateAWSAnalysisCosts(costData: any, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Parse aws-cost-cli data
    Object.entries(costData.services).forEach(([serviceName, serviceData]: [string, any]) => {
      if (serviceName.includes('Elastic Compute Cloud') || serviceName.includes('EKS')) {
        serviceData.resources.forEach((resource: any) => {
          if (resource.type.includes('EKS')) {
            breakdown.compute.kubernetes += resource.cost;
          } else {
            breakdown.compute.vm += resource.cost;
          }
        });
      } else if (serviceName.includes('Relational Database Service')) {
        breakdown.storage.database = serviceData.totalCost;
      } else if (serviceName.includes('Simple Storage Service')) {
        breakdown.storage.vmDisk = serviceData.totalCost;
      } else if (serviceName.includes('Elastic Load Balancing')) {
        breakdown.network.loadBalancer = serviceData.totalCost;
      } else {
        breakdown.other.management += serviceData.totalCost;
      }
    });

    // Estimate network data transfer (not directly from aws-cost-cli)
    breakdown.network.dataTransfer = Math.max(0, costData.totalMonthlyCost * 0.1); // Estimate 10% for data transfer

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = costData.totalMonthlyCost || Object.values(breakdown).reduce((sum, cat) => sum + cat.total, 0);

    // Generate recommendations based on actual usage
    if (breakdown.compute.vm > 200) {
      recommendations.push('Consider Reserved Instances for high EC2 costs');
    }

    if (breakdown.storage.database > 150) {
      recommendations.push('Consider Aurora Serverless for variable database workloads');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High actual monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'aws',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }
}

// =================================================================
// GCP COST ANALYSIS EQUIVALENTS
// =================================================================

export class GCPCostAnalyzer {
  private static readonly INFRACOST_CLI = 'infracost';
  private static readonly GCLOUD_CLI = 'gcloud';
  private static readonly GCP_COST_CLI = 'gcp-cost-cli';

  static isAvailable(): boolean {
    try {
      execSync(`${this.INFRACOST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      try {
        execSync(`${this.GCLOUD_CLI} version`, { stdio: 'ignore' });
        return true;
      } catch {
        try {
          execSync(`${this.GCP_COST_CLI} --version`, { stdio: 'ignore' });
          return true;
        } catch {
          return false;
        }
      }
    }
  }

  static isGCPCostCliAvailable(): boolean {
    try {
      execSync(`${this.GCP_COST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  static async getGCPPricing(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || config.region?.gcp || 'us-central1';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      console.warn('gcloud CLI or infracost not found, using fallback pricing estimation');
      return this.getFallbackGCPPricing(config, region, currency);
    }

    try {
      // Try to use infracost first (more comprehensive)
      if (this.isInfracostAvailable()) {
        return this.getInfracostPricing(config, region, currency);
      }
      // Fallback to GCP Billing API
      else {
        return this.getGCPPricingData(config, region, currency);
      }
    } catch (error) {
      console.warn('Failed to fetch GCP pricing data, using fallback:', error);
      return this.getFallbackGCPPricing(config, region, currency);
    }
  }

  private static isInfracostAvailable(): boolean {
    try {
      execSync(`${this.INFRACOST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  private static async getInfracostPricing(config: ChiralSystem, region: string, currency: string): Promise<CostEstimate> {
    // Generate temporary Terraform for infracost analysis
    const tempTfPath = await this.generateTempTerraform(config, region);
    
    try {
      // Run infracost breakdown
      const result = execSync(`${this.INFRACOST_CLI} breakdown --path ${tempTfPath} --format json`, { encoding: 'utf8' });
      const infracostData = JSON.parse(result);
      
      return this.parseInfracostData(infracostData, config, region, currency);
    } finally {
      // Clean up temp files
      try {
        fs.rmSync(tempTfPath, { recursive: true, force: true });
      } catch {
        // Ignore cleanup errors
      }
    }
  }

  private static async generateTempTerraform(config: ChiralSystem, region: string): Promise<string> {
    const tempDir = fs.mkdtempSync('chiral-gcp-cost-');
    const tfPath = path.join(tempDir, 'main.tf');
    
    // Generate minimal Terraform for cost estimation
    const tfContent = `
provider "google" {
  region = "${region}"
}

resource "google_container_cluster" "main" {
  name     = "${config.projectName}-gke"
  location = "${region}"
  
  remove_default_node_pool = true
  initial_node_count = 1

  min_master_version = "${config.k8s.version}"
}

resource "google_container_node_pool" "main" {
  name       = "${config.projectName}-nodes"
  cluster    = google_container_cluster.main.name
  location   = "${region}"
  
  node_count = ${config.k8s.maxNodes}
  node_config {
    machine_type = "${this.getGCPMachineType(config.k8s.size)}"
    oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  autoscaling {
    min_node_count = ${config.k8s.minNodes}
    max_node_count = ${config.k8s.maxNodes}
  }
}

resource "google_sql_database_instance" "main" {
  name             = "${config.projectName}-db"
  database_version = "POSTGRES_${config.postgres.engineVersion}"
  region           = "${region}"
  
  settings {
    tier = "${this.getGCPDatabaseTier(config.postgres.size)}"
    disk_size = ${config.postgres.storageGb}
  }
}

resource "google_compute_instance" "adfs" {
  name         = "${config.projectName}-adfs"
  machine_type = "${this.getGCPMachineType(config.adfs.size)}"
  zone         = "${region}-a"
  
  boot_disk {
    initialize_params {
      image = "windows-server-2019-dc-v20220112"
    }
  }
}
`;
    
    fs.writeFileSync(tfPath, tfContent);
    return tempDir;
  }

  private static parseInfracostData(data: any, config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Parse infracost data
    let totalMonthlyCost = 0;
    if (data.projects && data.projects[0] && data.projects[0].breakdown) {
      const breakdownData = data.projects[0].breakdown;
      
      breakdownData.resources?.forEach((resource: any) => {
        const cost = resource.monthlyCost || 0;
        totalMonthlyCost += cost;
        
        // Categorize costs
        if (resource.name.includes('gke') || resource.name.includes('container') || resource.name.includes('node')) {
          breakdown.compute.kubernetes += cost;
        } else if (resource.name.includes('instance')) {
          breakdown.compute.vm += cost;
        } else if (resource.name.includes('sql') || resource.name.includes('database')) {
          breakdown.storage.database += cost;
        } else if (resource.name.includes('disk') || resource.name.includes('storage')) {
          breakdown.storage.vmDisk += cost;
        } else if (resource.name.includes('network') || resource.name.includes('vpc')) {
          breakdown.network.dataTransfer += cost;
        } else if (resource.name.includes('lb') || resource.name.includes('load')) {
          breakdown.network.loadBalancer += cost;
        } else {
          breakdown.other.management += cost;
        }
      });
    }

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    // Generate recommendations
    if (config.environment === 'dev' && config.k8s.maxNodes > 3) {
      recommendations.push('Consider using e2-medium instances for development to save costs');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High estimated monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  private static async getGCPPricingData(config: ChiralSystem, region: string, currency: string): Promise<CostEstimate> {
    // Use GCP Billing Catalog API
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    try {
      // Get GKE pricing
      const gkePricing = await this.getGKEPricing(region);
      breakdown.compute.kubernetes = gkePricing.managementFee + (gkePricing.nodeCost * config.k8s.maxNodes);

      // Get Compute Engine pricing
      const computePricing = await this.getComputePricing(this.getGCPMachineType(config.k8s.size), region);
      breakdown.compute.vm = computePricing.hourly * 730; // Monthly approximation

      // Get Cloud SQL pricing
      const sqlPricing = await this.getCloudSQLPricingData(this.getGCPDatabaseTier(config.postgres.size), region);
      breakdown.storage.database = sqlPricing.compute + (config.postgres.storageGb * sqlPricing.storagePerGb);

      // Get networking costs
      breakdown.network.dataTransfer = 50 * 0.12; // 50GB data transfer
      breakdown.network.loadBalancer = 20; // Cloud Load Balancer monthly cost

      // Management and monitoring
      breakdown.other.management = 32;
      breakdown.other.monitoring = 16;

    } catch (error) {
      console.warn('GCP Billing API call failed, using estimates:', error);
      return this.getFallbackGCPPricing(config, region, currency);
    }

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Use Committed Use Discounts for predictable workloads'],
      warnings: []
    };
  }

  private static getFallbackGCPPricing(config: ChiralSystem, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    // Simplified fallback pricing
    breakdown.compute.kubernetes = config.k8s.maxNodes * 140; // GKE pricing
    breakdown.compute.vm = 90; // Compute Engine
    breakdown.storage.database = config.postgres.storageGb * 0.25 + 50; // Cloud SQL
    breakdown.storage.vmDisk = 17; // Persistent disk
    breakdown.network.dataTransfer = 22; // Data transfer
    breakdown.network.loadBalancer = 20; // Cloud Load Balancer
    breakdown.other.management = 32;
    breakdown.other.monitoring = 16;

    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Install infracost or gcloud CLI for more accurate pricing'],
      warnings: ['Using fallback pricing - install infracost for accurate costs']
    };
  }

  private static async getGKEPricing(region: string): Promise<{ managementFee: number; nodeCost: number }> {
    return { managementFee: 74, nodeCost: 66 }; // Simplified GKE pricing
  }

  private static async getCloudSQLPricingData(tier: string, region: string): Promise<{ compute: number; storagePerGb: number }> {
    const pricingMap: { [key: string]: { compute: number; storagePerGb: number } } = {
      'db-n1-standard-1': { compute: 25, storagePerGb: 0.17 },
      'db-n1-standard-2': { compute: 50, storagePerGb: 0.17 },
      'db-n1-standard-4': { compute: 100, storagePerGb: 0.17 }
    };
    return pricingMap[tier] || { compute: 50, storagePerGb: 0.17 };
  }

  private static async getComputePricing(machineType: string, region: string): Promise<{ hourly: number }> {
    const pricingMap: { [key: string]: number } = {
      'e2-medium': 0.069,
      'n1-standard-2': 0.133,
      'n1-standard-4': 0.266
    };
    return { hourly: pricingMap[machineType] || 0.133 };
  }

  private static getGCPMachineType(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'e2-micro',
      'large': 'n1-standard-4'
    };
    return sizeMap[size] || 'e2-micro';
  }

  private static getGCPDatabaseTier(size: string): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'db-n1-standard-1',
      'large': 'db-n1-standard-4'
    };
    return sizeMap[size] || 'db-n1-standard-2';
  }

  static async analyzeGCPCosts(projectId: string, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || 'us-central1';
    const currency = options.currency || 'USD';

    if (!this.isGCPCostCliAvailable()) {
      throw new Error('gcp-cost-cli not available. Install with: npm install -g gcp-cost-cli');
    }

    try {
      // Use gcp-cost-cli to analyze actual costs
      const costData = await this.fetchGCPCostData(projectId, region);
      return this.calculateGCPAnalysisCosts(costData, region, currency);
    } catch (error) {
      console.warn('Failed to analyze GCP costs:', error);
      throw error;
    }
  }

  private static async fetchGCPCostData(projectId: string, region: string): Promise<any> {
    // Use gcp-cost-cli to get actual billing data
    // This is a placeholder for actual gcp-cost-cli integration
    // Example: execSync(`gcp-cost-cli analyze --project ${projectId} --region ${region} --format json`);
    
    // For now, return mock data structure that gcp-cost-cli would provide
    return {
      projectId,
      region,
      services: {
        'Compute Engine': {
          totalCost: 220.40,
          resources: [
            { name: 'instance-1', cost: 75.20, type: 'VM Instance' },
            { name: 'gke-cluster-nodes', cost: 145.20, type: 'GKE Nodes' }
          ]
        },
        'Cloud SQL': {
          totalCost: 165.85,
          resources: [
            { name: 'postgres-instance', cost: 165.85, type: 'Cloud SQL Instance' }
          ]
        },
        'Cloud Storage': {
          totalCost: 38.75,
          resources: [
            { name: 'bucket-1', cost: 38.75, type: 'Storage Bucket' }
          ]
        }
      },
      totalMonthlyCost: 425.00
    };
  }

  private static calculateGCPAnalysisCosts(costData: any, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Parse gcp-cost-cli data
    Object.entries(costData.services).forEach(([serviceName, serviceData]: [string, any]) => {
      if (serviceName.includes('Compute Engine') || serviceName.includes('Kubernetes Engine')) {
        serviceData.resources.forEach((resource: any) => {
          if (resource.type.includes('GKE')) {
            breakdown.compute.kubernetes += resource.cost;
          } else {
            breakdown.compute.vm += resource.cost;
          }
        });
      } else if (serviceName.includes('Cloud SQL')) {
        breakdown.storage.database = serviceData.totalCost;
      } else if (serviceName.includes('Cloud Storage')) {
        breakdown.storage.vmDisk = serviceData.totalCost;
      } else if (serviceName.includes('Cloud Load Balancing')) {
        breakdown.network.loadBalancer = serviceData.totalCost;
      } else {
        breakdown.other.management += serviceData.totalCost;
      }
    });

    // Estimate network data transfer (not directly from gcp-cost-cli)
    breakdown.network.dataTransfer = Math.max(0, costData.totalMonthlyCost * 0.08); // Estimate 8% for data transfer

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = costData.totalMonthlyCost || Object.values(breakdown).reduce((sum, cat) => sum + cat.total, 0);

    // Generate recommendations based on actual usage
    if (breakdown.compute.vm > 180) {
      recommendations.push('Consider Committed Use Discounts for sustained compute usage');
    }

    if (breakdown.storage.database > 140) {
      recommendations.push('Consider Cloud SQL Enterprise edition for high-performance workloads');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High actual monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'gcp',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }
}

// =================================================================
// AZURE COST CLI INTEGRATION
// =================================================================

export class AzureCostAnalyzer {
  private static readonly AZURE_COST_CLI = 'azure-cost-cli';

  static isAvailable(): boolean {
    try {
      execSync(`${this.AZURE_COST_CLI} --version`, { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  static async analyzeAzureCosts(subscriptionId: string, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || 'East US';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      throw new Error('azure-cost-cli not available. Install with: npm install -g azure-cost-cli');
    }

    try {
      // Use azure-cost-cli to analyze actual costs
      const costData = await this.fetchAzureCostData(subscriptionId, region);
      return this.calculateAzureAnalysisCosts(costData, region, currency);
    } catch (error) {
      console.warn('Failed to analyze Azure costs:', error);
      throw error;
    }
  }

  private static async fetchAzureCostData(subscriptionId: string, region: string): Promise<any> {
    // Use azure-cost-cli to get actual billing data
    // This is a placeholder for actual azure-cost-cli integration
    // Example: execSync(`azure-cost-cli subscription --subscription ${subscriptionId} --format json`);
    
    // For now, return mock data structure that azure-cost-cli would provide
    return {
      subscriptionId,
      region,
      services: {
        'Virtual Machines': {
          totalCost: 180.50,
          resources: [
            { name: 'adfs-vm', cost: 180.50, type: 'VM Instance' }
          ]
        },
        'Container Instances': {
          totalCost: 220.30,
          resources: [
            { name: 'aks-cluster', cost: 220.30, type: 'AKS Cluster' }
          ]
        },
        'Azure Database for PostgreSQL': {
          totalCost: 195.75,
          resources: [
            { name: 'postgres-server', cost: 195.75, type: 'PostgreSQL Server' }
          ]
        },
        'Storage': {
          totalCost: 25.40,
          resources: [
            { name: 'storage-account', cost: 25.40, type: 'Storage Account' }
          ]
        }
      },
      totalMonthlyCost: 621.95
    };
  }

  private static calculateAzureAnalysisCosts(costData: any, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Parse azure-cost-cli data
    Object.entries(costData.services).forEach(([serviceName, serviceData]: [string, any]) => {
      if (serviceName.includes('Container Instances') || serviceName.includes('AKS')) {
        breakdown.compute.kubernetes = serviceData.totalCost;
      } else if (serviceName.includes('Virtual Machines')) {
        breakdown.compute.vm = serviceData.totalCost;
      } else if (serviceName.includes('PostgreSQL') || serviceName.includes('Database')) {
        breakdown.storage.database = serviceData.totalCost;
      } else if (serviceName.includes('Storage')) {
        breakdown.storage.vmDisk = serviceData.totalCost;
      } else if (serviceName.includes('Load Balancer') || serviceName.includes('Network')) {
        breakdown.network.loadBalancer = serviceData.totalCost;
      } else {
        breakdown.other.management += serviceData.totalCost;
      }
    });

    // Estimate network data transfer (not directly from azure-cost-cli)
    breakdown.network.dataTransfer = Math.max(0, costData.totalMonthlyCost * 0.05); // Estimate 5% for data transfer

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = costData.totalMonthlyCost || Object.values(breakdown).reduce((sum, cat) => sum + cat.total, 0);

    // Generate recommendations based on actual usage
    if (breakdown.compute.vm > 150) {
      recommendations.push('Consider Azure Reserved VM Instances for sustained compute usage');
    }

    if (breakdown.storage.database > 200) {
      recommendations.push('Consider Azure Database for PostgreSQL Hyperscale for high-performance workloads');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High actual monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'azure',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  static async getAzurePricing(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    const region = options.region || config.region?.azure || 'East US';
    const currency = options.currency || 'USD';

    if (!this.isAvailable()) {
      console.warn('azure-cost-cli not found, using fallback pricing estimation');
      return this.getFallbackAzurePricing(config, region, currency);
    }

    try {
      // Use azure-cost-cli for real pricing data
      const pricingData = await this.fetchAzurePricingData(config, region);
      return this.calculateAzureCosts(config, pricingData, region, currency);
    } catch (error) {
      console.warn('Failed to fetch Azure pricing data, using fallback:', error);
      return this.getFallbackAzurePricing(config, region, currency);
    }
  }

  private static async fetchAzurePricingData(config: ChiralSystem, region: string): Promise<any> {
    // This would use azure-cost-cli to fetch real pricing data
    // For now, we'll implement a placeholder that would be replaced with actual CLI calls
    
    // Example of what the azure-cost-cli integration might look like:
    // const result = execSync(`${this.AZURE_COST_CLI} prices --region "${region}" --service "Virtual Machines" --sku "Standard_D4s_v3"`, { encoding: 'utf8' });
    
    return {
      virtualMachines: await this.getVMPricing(region),
      kubernetes: await this.getAKSPricing(region),
      databases: await this.getPostgresPricing(region),
      storage: await this.getStoragePricing(region),
      networking: await this.getNetworkingPricing(region)
    };
  }

  private static async getVMPricing(region: string): Promise<any> {
    // Placeholder for azure-cost-cli VM pricing call
    // execSync(`${this.AZURE_COST_CLI} prices --region "${region}" --service "Virtual Machines"`);
    return {
      'Standard_D2s_v3': { hourly: 0.096, monthly: 69.12 },
      'Standard_D4s_v3': { hourly: 0.192, monthly: 138.24 },
      'Standard_D8s_v3': { hourly: 0.384, monthly: 276.48 }
    };
  }

  private static async getAKSPricing(region: string): Promise<any> {
    // Placeholder for azure-cost-cli AKS pricing call
    return {
      managementFee: { monthly: 0.10 }, // $0.10 per cluster per hour
      nodePools: {
        'Standard_B2s': { hourly: 0.041, monthly: 29.52 },
        'Standard_D4s_v3': { hourly: 0.192, monthly: 138.24 }
      }
    };
  }

  private static async getPostgresPricing(region: string): Promise<any> {
    // Placeholder for azure-cost-cli PostgreSQL pricing call
    return {
      flexibleServer: {
        'Standard_B2s': { hourly: 0.051, monthly: 36.72 },
        'Standard_D4s_v3': { hourly: 0.204, monthly: 146.88 },
        storage: { perGb: 0.115 } // $0.115 per GB-month
      }
    };
  }

  private static async getStoragePricing(region: string): Promise<any> {
    // Placeholder for azure-cost-cli storage pricing call
    return {
      premiumSSD: { perGb: 0.115 },
      standardSSD: { perGb: 0.06 },
      managedDiskOS: { perGb: 0.06 }
    };
  }

  private static async getNetworkingPricing(region: string): Promise<any> {
    // Placeholder for azure-cost-cli networking pricing call
    return {
      dataTransfer: { perGb: 0.087 },
      loadBalancer: { monthly: 18.00 },
      publicIP: { monthly: 3.60 }
    };
  }

  private static calculateAzureCosts(config: ChiralSystem, pricingData: any, region: string, currency: string): CostEstimate {
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    const recommendations: string[] = [];
    const warnings: string[] = [];

    // Kubernetes costs
    const k8sSku = this.getK8sSku(config);
    const k8sNodeCost = pricingData.kubernetes.nodePools[k8sSku]?.monthly || 138.24;
    const k8sManagementCost = pricingData.kubernetes.managementFee.monthly * 24 * 30; // $0.10/hour
    breakdown.compute.kubernetes = (k8sNodeCost * config.k8s.maxNodes) + k8sManagementCost;

    // VM costs (ADFS)
    const vmSku = this.getVMSku(config);
    const vmCost = pricingData.virtualMachines[vmSku]?.monthly || 69.12;
    breakdown.compute.vm = vmCost;

    // Database costs
    const dbSku = this.getDbSku(config);
    const dbComputeCost = pricingData.databases.flexibleServer[dbSku]?.monthly || 36.72;
    const dbStorageCost = config.postgres.storageGb * pricingData.databases.flexibleServer.storage.perGb;
    breakdown.storage.database = dbComputeCost + dbStorageCost;

    // VM disk costs
    const vmDiskCost = 128 * pricingData.storage.managedDiskOS.perGb; // Assume 128GB OS disk
    breakdown.storage.vmDisk = vmDiskCost;

    // Networking costs
    breakdown.network.loadBalancer = pricingData.networking.loadBalancer.monthly;
    breakdown.network.dataTransfer = 100 * pricingData.networking.dataTransfer.perGb; // Assume 100GB data transfer

    // Management and monitoring
    breakdown.other.management = 50; // Estimated management overhead
    breakdown.other.monitoring = 20; // Estimated monitoring costs

    // Calculate totals
    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    // Generate recommendations
    if (config.environment === 'dev' && config.k8s.maxNodes > 3) {
      recommendations.push('Consider reducing max nodes for development environment to save costs');
    }

    if (config.postgres.storageGb > 1000) {
      recommendations.push('Consider database sharding for storage over 1TB');
    }

    if (totalMonthlyCost > 1000) {
      warnings.push(`High estimated monthly cost: $${totalMonthlyCost.toFixed(2)}`);
    }

    return {
      provider: 'azure',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations,
      warnings
    };
  }

  private static getFallbackAzurePricing(config: ChiralSystem, region: string, currency: string): CostEstimate {
    // Fallback pricing when azure-cost-cli is not available
    const breakdown: CostBreakdown = {
      compute: { kubernetes: 0, vm: 0, total: 0 },
      storage: { database: 0, vmDisk: 0, total: 0 },
      network: { dataTransfer: 0, loadBalancer: 0, total: 0 },
      other: { management: 0, monitoring: 0, total: 0 }
    };

    // Simplified fallback pricing
    breakdown.compute.kubernetes = config.k8s.maxNodes * 150; // $150 per node per month
    breakdown.compute.vm = 100; // $100 for ADFS VM
    breakdown.storage.database = config.postgres.storageGb * 0.15 + 50; // $0.15/GB + base cost
    breakdown.storage.vmDisk = 20; // $20 for VM disk
    breakdown.network.dataTransfer = 20; // $20 for data transfer
    breakdown.network.loadBalancer = 18; // $18 for load balancer
    breakdown.other.management = 30;
    breakdown.other.monitoring = 15;

    breakdown.compute.total = breakdown.compute.kubernetes + breakdown.compute.vm;
    breakdown.storage.total = breakdown.storage.database + breakdown.storage.vmDisk;
    breakdown.network.total = breakdown.network.dataTransfer + breakdown.network.loadBalancer;
    breakdown.other.total = breakdown.other.management + breakdown.other.monitoring;

    const totalMonthlyCost = Object.values(breakdown).reduce((sum, category) => sum + category.total, 0);

    return {
      provider: 'azure',
      totalMonthlyCost,
      currency,
      breakdown,
      recommendations: ['Install azure-cost-cli for more accurate pricing'],
      warnings: ['Using fallback pricing - install azure-cost-cli for accurate costs']
    };
  }

  private static getK8sSku(config: ChiralSystem): string {
    // Map size to Azure SKU - this should match the mapping in azure-bicep.ts
    const sizeMap: { [key: string]: string } = {
      'small': 'Standard_B2s',
      'medium': 'Standard_D4s_v3',
      'large': 'Standard_D8s_v3'
    };
    return sizeMap[config.k8s.size] || 'Standard_D4s_v3';
  }

  private static getVMSku(config: ChiralSystem): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'Standard_B1s',
      'medium': 'Standard_D4s_v3',
      'large': 'Standard_D8s_v3'
    };
    return sizeMap[config.adfs.size] || 'Standard_B1s';
  }

  private static getDbSku(config: ChiralSystem): string {
    const sizeMap: { [key: string]: string } = {
      'small': 'Standard_B2s',
      'medium': 'Standard_D4s_v3',
      'large': 'Standard_D8s_v3'
    };
    return sizeMap[config.postgres.size] || 'Standard_D4s_v3';
  }
}

// =================================================================
// MULTI-CLOUD COST COMPARISON
// =================================================================

export class CostAnalyzer {
  static async compareCosts(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostComparison> {
    const [awsEstimate, azureEstimate, gcpEstimate] = await Promise.all([
      AWSCostAnalyzer.getAWSPricing(config, options),
      AzureCostAnalyzer.getAzurePricing(config, options),
      GCPCostAnalyzer.getGCPPricing(config, options)
    ]);

    const estimates = { aws: awsEstimate, azure: azureEstimate, gcp: gcpEstimate };
    
    const costs = [
      { provider: 'aws' as const, cost: awsEstimate.totalMonthlyCost },
      { provider: 'azure' as const, cost: azureEstimate.totalMonthlyCost },
      { provider: 'gcp' as const, cost: gcpEstimate.totalMonthlyCost }
    ].sort((a, b) => a.cost - b.cost);

    const cheapest = costs[0];
    const mostExpensive = costs[2];
    const savings = ((mostExpensive.cost - cheapest.cost) / mostExpensive.cost) * 100;

    return {
      cheapest: {
        provider: cheapest.provider,
        cost: cheapest.cost,
        savings: Math.round(savings * 100) / 100
      },
      mostExpensive: {
        provider: mostExpensive.provider,
        cost: mostExpensive.cost
      },
      estimates
    };
  }

  static async getAWSEstimate(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    return AWSCostAnalyzer.getAWSPricing(config, options);
  }

  static async getGCPEstimate(config: ChiralSystem, options: CostAnalysisOptions = {}): Promise<CostEstimate> {
    return GCPCostAnalyzer.getGCPPricing(config, options);
  }

  static generateCostReport(comparison: CostComparison, options: CostAnalysisOptions = {}): string {
    const { cheapest, mostExpensive, estimates } = comparison;
    
    let report = `\n📊 Cost Analysis Report\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    report += `💰 **Summary**\n`;
    report += `Cheapest: ${cheapest.provider.toUpperCase()} ($${cheapest.cost.toFixed(2)}/month)\n`;
    report += `Most Expensive: ${mostExpensive.provider.toUpperCase()} ($${mostExpensive.cost.toFixed(2)}/month)\n`;
    report += `Potential Savings: ${cheapest.savings}% with ${cheapest.provider.toUpperCase()}\n\n`;

    if (options.detailed) {
      report += `📈 **Detailed Breakdown**\n`;
      Object.entries(estimates).forEach(([provider, estimate]) => {
        report += `\n${provider.toUpperCase()}:\n`;
        report += `  Total: $${estimate.totalMonthlyCost.toFixed(2)}/month\n`;
        report += `  Compute: $${estimate.breakdown.compute.total.toFixed(2)}\n`;
        report += `  Storage: $${estimate.breakdown.storage.total.toFixed(2)}\n`;
        report += `  Network: $${estimate.breakdown.network.total.toFixed(2)}\n`;
        report += `  Other: $${estimate.breakdown.other.total.toFixed(2)}\n`;
        
        if (estimate.recommendations.length > 0) {
          report += `  Recommendations:\n`;
          estimate.recommendations.forEach(rec => report += `    • ${rec}\n`);
        }
        
        if (estimate.warnings.length > 0) {
          report += `  Warnings:\n`;
          estimate.warnings.forEach(warn => report += `    ⚠️  ${warn}\n`);
        }
      });
    }

    return report;
  }
}

// =================================================================
// COST OPTIMIZATION RECOMMENDATIONS
// =================================================================

export class CostOptimizer {
  static analyzeConfiguration(config: ChiralSystem): string[] {
    const recommendations: string[] = [];

    // Kubernetes optimization
    if (config.k8s.maxNodes > 10 && config.environment === 'dev') {
      recommendations.push('Development environment: Consider reducing max nodes from ' + 
        `${config.k8s.maxNodes} to 3-5 for cost savings`);
    }

    if (config.k8s.minNodes === config.k8s.maxNodes && config.environment === 'prod') {
      recommendations.push('Production environment: Enable autoscaling by setting maxNodes > minNodes');
    }

    // Database optimization
    if (config.postgres.storageGb > 500 && config.environment === 'dev') {
      recommendations.push('Development database: Consider reducing storage from ' + 
        `${config.postgres.storageGb}GB to 100-200GB`);
    }

    // Network optimization
    if (config.networkCidr === '10.0.0.0/16' && config.environment === 'dev') {
      recommendations.push('Consider using a smaller network CIDR for development (e.g., 10.0.0.0/20)');
    }

    return recommendations;
  }

  static suggestCostEffectiveAlternatives(config: ChiralSystem): Array<{provider: string, reason: string, savings: string}> {
    const alternatives: Array<{provider: string, reason: string, savings: string}> = [];

    // This would analyze the config and suggest alternatives
    // For now, return some example suggestions
    
    if (config.environment === 'dev') {
      alternatives.push({
        provider: 'GCP',
        reason: 'GCP offers competitive pricing for development workloads',
        savings: 'Up to 15% compared to AWS'
      });
    }

    if (config.k8s.maxNodes <= 3) {
      alternatives.push({
        provider: 'Azure',
        reason: 'Azure has competitive pricing for small Kubernetes clusters',
        savings: 'Up to 10% for small clusters'
      });
    }

    return alternatives;
  }
}
